In [1]:
import numpy as np

In [2]:
# Generate NumPy array.

arr1 = np.array(range(1, 11))
print arr1 ** 0.5

[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766]


In [3]:
# Create NumPy array and convert to two dimensions.

arr2 = np.array(range(10)).reshape(2, 5)
print arr2

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
# Using different functions and methods on a NumPy array.

print np.argmin(arr2[1])
print max(arr2[1])
print np.sum(arr2)
print arr2.shape

0
9
45
(2, 5)


In [5]:
# Using vectorized operations, boolean comparisons, and additional functions with NumPy array.

z = np.array([7, 8, 9])
print z == [7, 7, 7]
print z + 2
print z >= 8
print max(z)
print np.mean(z)
print np.std(z)

[ True False False]
[ 9 10 11]
[False  True  True]
9
8.0
0.816496580928


In [6]:
# Indexing a 3D NumPy array.

arr3d = np.arange(30).reshape(2, 3, 5)
print arr3d

# Providing one index.
print "\nIndexing:\n", arr3d[1]

# Providing two indices.
print "\nIndexing:\n", arr3d[1][2]

# Providing three indicies
print "\nIndexing:\n", arr3d[1][2][3]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

Indexing:
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Indexing:
[25 26 27 28 29]

Indexing:
28


In [7]:
# Indexing within one set of brackets across all three dimensions using slicing.
print arr3d[1, 1:, 0:2]

[[20 21]
 [25 26]]


In [8]:
# Using boolean to create slice of the 3D NumPy array.
print arr3d[arr3d % 3 == 1]

[ 1  4  7 10 13 16 19 22 25 28]


In [9]:
# Indexing a NumPy, which provides views of the source array. Any modifications made to them affect the source!

arr = np.arange(10)
print arr

arr_slice = arr[0:3]
print arr_slice

arr_slice[0] = 2000

print arr_slice
print arr

# To make a copy of an array, use the copy() method.

arr_copy = arr.copy()

print arr_copy
arr_copy_slice = arr_copy[0:3]
arr_copy_slice[:] = 108

print arr_copy
print arr

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[2000    1    2]
[2000    1    2    3    4    5    6    7    8    9]
[2000    1    2    3    4    5    6    7    8    9]
[108 108 108   3   4   5   6   7   8   9]
[2000    1    2    3    4    5    6    7    8    9]


In [10]:
# Using broadcasting to use one array to index another.

boolarray = np.array(["Adam", "Lee", "Margreth"])
arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

# Generates array of values from arr2d using "Adam" as the index.
print arr2d[boolarray == "Adam"], '\n'

# Creates mask with which to index second array.
mask = (boolarray == "Adam") | (boolarray == "Lee")
print mask

print arr2d[mask]


[[1 2 3 4]] 

[ True  True False]
[[1 2 3 4]
 [4 5 6 7]]


In [11]:
# NumPy exp() function takes the base of the natural logarithm (Euler's number)
# to the power of each number in the array passed in.

arr1 = np.arange(5)
print np.exp(arr1)

[  1.           2.71828183   7.3890561   20.08553692  54.59815003]


In [12]:
# linspace() function creates an array of equidistant values ranging from
# the start value to the stop value (default steps = 50)

print np.linspace(1, 10)

print np.linspace(5, 10, 3)

[  1.           1.18367347   1.36734694   1.55102041   1.73469388
   1.91836735   2.10204082   2.28571429   2.46938776   2.65306122
   2.83673469   3.02040816   3.20408163   3.3877551    3.57142857
   3.75510204   3.93877551   4.12244898   4.30612245   4.48979592
   4.67346939   4.85714286   5.04081633   5.2244898    5.40816327
   5.59183673   5.7755102    5.95918367   6.14285714   6.32653061
   6.51020408   6.69387755   6.87755102   7.06122449   7.24489796
   7.42857143   7.6122449    7.79591837   7.97959184   8.16326531
   8.34693878   8.53061224   8.71428571   8.89795918   9.08163265
   9.26530612   9.44897959   9.63265306   9.81632653  10.        ]
[  5.    7.5  10. ]


In [13]:
# NumPt dot() function adds together the products of multiplying across matricies.

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print np.dot(a, b)

70


In [14]:
# Creating NumPy arrays with alternative functions (zeros(), ones(), and full(), and empty()).

a = np.zeros([2, 2])
print a

b = np.ones([2, 2])
print b

c = np.full([2, 3], 8)
print c

d = np.empty([3, 2])
print d

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 8.  8.  8.]
 [ 8.  8.  8.]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


/Users/adamweber/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:294: FutureWarning: in the future, full([2, 3], 8) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [15]:
# Using flat iterator and ravel() method.

a = np.arange(24).reshape(2, 2, 6)
print a

for item in a.flat:
    print item,

b = a.ravel()
print '\n', b

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
# Using NumPy np.add() function to perform arithmetics on arrays (takes place elementwise)

a = np.arange(10)*3

b = np.arange(10)*2

# Both do the same. Works the same way with np.subtract/multiply/divide
print np.add(a, b)

print a + b

[ 0  5 10 15 20 25 30 35 40 45]
[ 0  5 10 15 20 25 30 35 40 45]
